return {
    ["workshop-356420397"]={ configuration_options={  }, enabled=true },
    ["workshop-375859599"]={
        configuration_options={
            divider=5,
            random_health_value=0,
            random_range=0,
            show_type=0,
            unknwon_prefabs=1,
            use_blacklist=true 
        },
        enabled=true 
    },
    ["workshop-378160973"]={
        configuration_options={
            ENABLEPINGS=true,
            FIREOPTIONS=2,
            OVERRIDEMODE=false,
            SHAREMINIMAPPROGRESS=true,
            SHOWFIREICONS=true,
            SHOWPLAYERICONS=true,
            SHOWPLAYERSOPTIONS=2 
        },
        enabled=true 
    },
    ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
    ["workshop-462434129"]={
        configuration_options={
            MOD_RESTART_ALLOW_KILL=true,
            MOD_RESTART_ALLOW_RESTART=true,
            MOD_RESTART_ALLOW_RESURRECT=true,
            MOD_RESTART_CD_BONUS=0,
            MOD_RESTART_CD_KILL=3,
            MOD_RESTART_CD_MAX=0,
            MOD_RESTART_CD_RESTART=5,
            MOD_RESTART_CD_RESURRECT=7,
            MOD_RESTART_FORCE_DROP_MODE=2,
            MOD_RESTART_IGNORING_ADMIN=true,
            MOD_RESTART_MAP_SAVE=2,
            MOD_RESTART_RESURRECT_HEALTH=100,
            MOD_RESTART_TRIGGER_MODE=1,
            MOD_RESTART_WELCOME_TIPS=true,
            MOD_RESTART_WELCOME_TIPS_TIME=6 
        },
        enabled=true 
    },
    ["workshop-462469447"]={ configuration_options={  }, enabled=true },
    ["workshop-503187227"]={
        configuration_options={
            [""]=0,
            AltarRoomOption=2,
            AncientGuardianSpawn=1,
            BrokenAltarOption=2,
            CaveBaseOption=12,
            ChessSpot1Option=1,
            ChessSpot2Option=1,
            ChessSpot3Option=1,
            Chessy1Option=2,
            Chessy2Option=2,
            Chessy3Option=2,
            Chessy4Option=2,
            Chessy5Option=2,
            Chessy6Option=2,
            DeciduousPondOption=3,
            DefaultPigkingOption=1,
            DragonflySpawn=1,
            FarmplotOption=8,
            FisherPigOption=1,
            GlobalBiomeSize=3,
            GrottoOption=20,
            InfusedWorldsRandomOptionalBiomes=15,
            LightsOutStartingItems=0,
            LivingTreeOption=2,
            MacTuskCityOption=1,
            MacTuskTownOption=1,
            Maxwell1Option=1,
            Maxwell2Option=1,
            Maxwell3Option=1,
            Maxwell4Option=1,
            Maxwell5Option=1,
            Maxwell6Option=1,
            Maxwell7Option=1,
            MermShrineOption=0,
            MilitaryEntranceOption=1,
            MooseSpawn=9,
            MushBaseOption=12,
            OverworldNightmarePhase=1,
            PigGuardsOption=2,
            PigShrineOption=0,
            PigTownOption=2,
            RabbitTownOption=8,
            RandomOptionalBiomes=6,
            RandomOptionalCaveBiomes=8,
            ResurrectionStoneOption=2,
            RuinedBaseOption=2,
            RuinsCampOption=5,
            SimpleBaseOption=2,
            SinkBaseOption=12,
            SpiralOption=2,
            StoneHengeOption=8,
            SwampPigOption=1,
            TorchPigkingOption=1,
            VillageSquareOption=2 
        },
        enabled=true 
    },
    ["workshop-595764362"]={
        configuration_options={
            Connections={ ["1"]={ "2","2","2","2","2", "3","3","3","3","3" }, ["2"]={ "3","3","3","3","3" },
            DeleteUnused=false,
            OneWayConnections={  },
            SyncFromMaster=true 
        },
        enabled=true 
    },
    ["workshop-656256171"]={
        configuration_options={ dont_give_dubloons=2, give_dubloons=1, position=1, rec_dubloon=3, rec_gold=3 },
        enabled=true 
    },
    ["workshop-666155465"]={
        configuration_options={
            food_estimation=-1,
            food_order=0,
            food_style=0,
            lang="auto",
            show_food_units=-1 
        },
        enabled=true 
    },
    ["workshop-1084023218"]={ configuration_options={ Language=true  }, enabled=true  },
    ["workshop-439115156"]={
        configuration_options={
            avisual_musha="Bmm",
            avisual_pirate="BL",
            avisual_pirate_armor="pirate",
            avisual_princess="WSP",
            badge_type=2,
            bodyguardwilson=0,
            craftgems="color",
            deathPenalty="on",
            dietmusha="normal",
            difficultdamage="normal",
            difficultdamage_range="normal",
            difficulthealth="normal",
            difficultmusic="dmusic_normal",
            difficultover="monster1x",
            difficultrecipe="normal",
            difficultsanity="normal",
            difficultsleep="dsleep_normal",
            difficulttired="dtired_normal",
            favoritemusha="normal",
            frostblade3rd=1,
            incontainer=0,
            key=108,
            key10=110,
            key11=103,
            key12=116,
            key13=282,
            key14=283,
            key15=111,
            key16=285,
            key2=114,
            key3=99,
            key4=120,
            key5=107,
            key6=122,
            key7=112,
            key8=118,
            key9=98,
            loudlightning="off",
            musha_incontainer=1,
            on_butterfly_shield=1,
            princess_taste="princess",
            shareitems=0,
            smartmusha="normal",
            stop_spawning=1 

        },
        enabled=true 

    } 

}
